title: Mos
logo: /assets/img/headshot_\New_Project_(7)--rr_7Foiw-transformed](https://github.com/TheFireLightning/TheFireLightning.github.io/assets/139693090/386c346e-3f66-423f-8b96-f6ee6b64fb43
description: My Portfolio
show_downloads: false
theme: jekyll-theme-minimal
